Universe       = vanilla
Notification   = never
Priority       = +10
GetEnv         = true
Executable     = /usr/bin/singularity
Arguments      = "exec -e -B /direct -B /star -B /afs -B /gpfs -B /sdcc/lustre02 /cvmfs/star.sdcc.bnl.gov/containers/rhic_sl7.sif /star/u/yghuang/miniconda3/bin/python3 deploy.py"
Log            = .Deploy.log
Output         = .Deploy.out
Error          = .Deploy.err
Queue
