Universe       = vanilla
Notification   = never
Priority       = +10
GetEnv         = true
Executable     = /usr/bin/singularity
Arguments      = "exec -e -B /direct -B /star -B /afs -B /gpfs -B /sdcc/lustre02 /cvmfs/star.sdcc.bnl.gov/containers/rhic_sl7.sif /star/u/yghuang/miniconda3/bin/python3 merge.py TASKNAME SCANNAME ITERID MERGEID FLIST TDIR"
Log            = .SCANNAME.log
Output         = .SCANNAME.out
Error          = .SCANNAME.err
Queue
